version: '3'
services:
 dbpostgres:
  build: ./postgres
  volumes:
   - /private/var/lib/postgresql:/var/lib/postgresql/data
  ports:
   - "5432:5432"
  environment:
   POSTGRES_USER: user
   POSTGRES_PASSWORD: db1234
   POSTGRES_DB: mantenimientodb
  deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
 micro1:
  build : ./payara
  depends_on:
   - dbpostgres
  ports:
   - "8080:8080"
  volumes:
   - ./payara-micro/deployments:/opt/payara/deployments
  deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
 httpd1:
  build: ./httpd
  deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
  volumes:
      - ./:/usr/local/apache2/htdocs/
  ports:
      - "80:80"
 sonarqube:
  image: sonarqube:6.7.1
  restart: always
  ports:
   - "9000:9000"
  environment:
   - SONARQUBE_JDBC_USERNAME= user
   - SONARQUBE_JDBC_PASSWORD= db1234
   - SONARQUBE_JDBC_URL=jdbc:postgresql://192.168.0.21:5432/mantenimientodb
  volumes:
   - sonarqube_conf:/opt/sonarqube/conf
   - sonarqube_data:/opt/sonarqube/data
   - sonarqube_extensions:/opt/sonarqube/extensions
   - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
