version: '3'
services:
 dbpostgres:
  build: ./postgres
  volumes:
   - /private/var/lib/postgresql:/var/lib/postgresql/data
  ports:
   - "5432:5432"
  environment:
   POSTGRES_USER: user
   POSTGRES_PASSWORD: db1234
   POSTGRES_DB: mantenimientodb
  deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
 micro1:
  build : ./payara
  depends_on:
   - dbpostgres
  ports:
   - "8080:8080"
  volumes:
   - ./payara-micro/deployments:/opt/payara/deployments
  deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
