version: "3"
services:
  dbpostgres:    
    build: ./postgres
    image: 192.168.0.21:5000/dbpostgres
    volumes:
      - vol-dbpostgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: db1234
     POSTGRES_DB: mantenimientodb
  deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
  web:    
    build: ./payara
    image: 192.168.0.21:5000/web-payara
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgres
  deploy:
      restart_policy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
volumes:
  vol-dbpostgres:
