version: "3"
services:
  dbpostgres:    
    build: ./postgres
    image: private:5000/dbpostgres
    volumes:
      - vol-dbpostgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: db1234
     POSTGRES_DB: mantenimientodb
  web:    
    build: ./payara
    image: private:5000/web-payara
    ports:
      - "8084:8080"
    depends_on:
      - dbpostgres
volumes:
  vol-dbpostgres:
